## Why Python Built-in Data Structures?

* To collect multiple data in a structure.

#### 4 Data Structures in python
1. List
2. Sets
3. Tuples
4. Dictionary - Key & Value pair

## 1.List

In [1]:
student_marks = 67,78,10,100,90
student_marks

(67, 78, 10, 100, 90)

In [2]:
type(student_marks)

tuple

In [3]:
empty_cart = []

In [4]:
empty_cart

[]

In [5]:
type(empty_cart)

list

In [14]:
items_to_buy = ["apples","Grapes","Mangoes","Banana","apples"] # accpets the duplicate
items_to_buy

['apples', 'Grapes', 'Mangoes', 'Banana', 'apples']

In [13]:
type(items_to_buy)

list

In [16]:
items_to_buy = ["apples","Grapes","Mangoes","Banana","apples",6.68,10,7.78] #it collectes both String and float
items_to_buy

['apples', 'Grapes', 'Mangoes', 'Banana', 'apples', 6.68, 10, 7.78]

In [17]:
len(items_to_buy) # how many items are there in that particular varibale

8

In [19]:
items_to_buy[0] # Indexing - cutting the portion of whole value to get particular value.

'apples'

In [22]:
items_to_buy[3]

'Banana'

In [23]:
items_to_buy[-3]

6.68

In [25]:
items_to_buy[0:3]

['apples', 'Grapes', 'Mangoes']

In [26]:
items_to_buy[1:5 # Positive Indexing

['Grapes', 'Mangoes', 'Banana', 'apples']

In [27]:
items_to_buy[-6:-3 #Negative Indexing

['Mangoes', 'Banana', 'apples']

In [28]:
 items_to_buy

['apples', 'Grapes', 'Mangoes', 'Banana', 'apples', 6.68, 10, 7.78]

In [31]:
 items_to_buy[5] = "watermelon" # mutubale which means to update the value or changing the value

In [32]:
 items_to_buy

['apples', 'Grapes', 'Mangoes', 'Banana', 'apples', 'watermelon', 10, 7.78]

In [36]:
 items_to_buy[4]= "Orange"

In [35]:
 items_to_buy

['apples', 'Grapes', 'Mangoes', 'Banana', 'Orange', 'watermelon', 10, 7.78]

# 2. Sets

In [40]:
empty_cart_2 = set()

In [41]:
empty_cart_2

set()

In [42]:
type(empty_cart_2)

set

In [50]:
items_to_buy_2 = {"apples","Grapes","Mangoes","Banana","apples"}

In [51]:
items_to_buy_2

{'Banana', 'Grapes', 'Mangoes', 'apples'}

In [52]:
type(items_to_buy_2)

set

In [62]:
items_to_buy_2 = {"Apples","Grapes","Mangoes","Banana","Apples",6.68,10,7.78}

In [63]:
items_to_buy_2

{10, 6.68, 7.78, 'Apples', 'Banana', 'Grapes', 'Mangoes'}

In [70]:
items_to_buy_2.add("Orange") # to add the value

In [86]:
items_to_buy_2

{'Onion'}

In [67]:
items_to_buy_2.discard("Grapes") #to remove the

In [68]:
items_to_buy_2

{10, 6.68, 7.78, 'Apples', 'Banana', 'Mangoes', 'Orange'}

In [71]:
items_to_buy_2.difference(items_to_buy)

{6.68, 'Apples'}

In [80]:
items_to_buy_2.clear()

In [76]:
items_to_buy_2

set()

In [83]:
items_to_buy_2.update({"Onion"})

In [84]:
items_to_buy_2

{'Onion'}

In [85]:
items_to_buy_2

{'Onion'}

In [87]:
items_to_buy_2 = {"Apples","Grapes","Mangoes","Banana","Apples",6.68,10,7.78}

# 3. Tuple

In [97]:
empty_cart_3 = () #empty Tuple

In [98]:
empty_cart_3

()

In [99]:
type(empty_cart_3)

tuple

In [100]:
items_to_buy_3 = ("apples","Grapes","Mangoes","Banana","apples",6.8,8,9)

In [101]:
items_to_buy_3

('apples', 'Grapes', 'Mangoes', 'Banana', 'apples', 6.8, 8, 9)

In [102]:
items_to_buy_3[0]

'apples'

In [103]:
items_to_buy_3[0:4]

('apples', 'Grapes', 'Mangoes', 'Banana')

In [104]:
items_to_buy_3.count("apples") #how many times repeat in the value

2

In [106]:
items_to_buy_3.index("Grapes") # In which position the particular value stored

1

# 4. Dictionary (It is a key value pair)

In [107]:
empty_cart_4 = {}
empty_cart_4

{}

In [108]:
type(empty_cart_4 )

dict

In [2]:
student_marks = {"Maths" :89,
                 "English":90,
                "Scinece":100}

In [3]:
student_marks

{'Maths': 89, 'English': 90, 'Scinece': 100}

In [4]:
type(student_marks)

dict

In [10]:
items_to_buy_4 = {"potato":5, "Toamato":2,"Apple":3}
items_to_buy_4

{'potato': 5, 'Toamato': 2, 'Apple': 3}

In [13]:
type(items_to_buy_4)

dict

In [12]:
items_to_buy_4 = {"potato":5, "Toamato":2,"Apple":3,"potato":6}
items_to_buy_4  # put Duplicate key but the latest value only derived in the output

{'potato': 6, 'Toamato': 2, 'Apple': 3}

In [14]:
items_to_buy_4.keys()

dict_keys(['potato', 'Toamato', 'Apple'])

In [15]:
items_to_buy_4.values()

dict_values([6, 2, 3])

In [20]:
import pandas as pd

In [ ]:
pd.DataFrame(data=items_to_buy_4) # this one is not called due to this does not have any rows and column value and it is value error

In [2]:
math_student_marks = {"Class1":[67,68,90,100,87]} #expected after dictionary key more than one values then we need to use other data structure here we will use List[]
math_student_marks

{'Class1': [67, 68, 90, 100, 87]}

In [3]:
import pandas as pd

In [4]:
pd.DataFrame(math_student_marks)

   Class1
0      67
1      68
2      90
3     100
4      87

In [32]:
math_student_marks = {"Name":["Hari", "kalai", "priya", "hema", "Guna"],
                    "Maths":[67,68,90,100,87],
                     "Science":[100,90,60,40,89]}
math_student_marks

{'Name': ['Hari', 'kalai', 'priya', 'hema', 'Guna'],
 'Maths': [67, 68, 90, 100, 87],
 'Science': [100, 90, 60, 40, 89]}

In [33]:
pd.DataFrame(math_student_marks)

    Name  Maths  Science
0   Hari     67      100
1  kalai     68       90
2  priya     90       60
3   hema    100       40
4   Guna     87       89

# THE END of DATA Structures